# Generated by Django 3.2.7 on 2021-10-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_completed', models.BooleanField(blank=True, null=True)),
                ('employer_completed', models.BooleanField(blank=True, null=True)),
                ('app_status', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSection',
            fields=[
                ('application_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('agency', models.CharField(blank=True, max_length=30)),
                ('dept_name', models.CharField(blank=True, max_length=30)),
                ('dept_grant_no', models.CharField(max_length=5)),
                ('pos_sched', models.CharField(blank=True, max_length=10)),
                ('pos_title', models.CharField(blank=True, max_length=30)),
                ('job_loc', models.CharField(blank=True, max_length=30)),
                ('source_funds', models.CharField(blank=True, max_length=20)),
                ('award_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('grant_no', models.CharField(blank=True, max_length=10)),
                ('acct_sign', models.CharField(blank=True, max_length=20)),
                ('hire_period', models.CharField(blank=True, max_length=15)),
                ('begin_date', models.DateField(blank=True)),
                ('pay_grade', models.CharField(blank=True, max_length=10)),
                ('rate_of_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('responsible', models.CharField(blank=True, max_length=20)),
                ('resp_title', models.CharField(blank=True, max_length=30)),
                ('signature', models.CharField(blank=True, max_length=20)),
                ('name_dept_head', models.CharField(blank=True, max_length=20)),
                ('date_signed', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('application', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ric_student', models.CharField(blank=True, max_length=7)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('m_initial', models.CharField(blank=True, max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('ric_email', models.EmailField(blank=True, max_length=45)),
                ('candidate_degree', models.CharField(blank=True, max_length=13)),
                ('number_credits', models.SmallIntegerField(blank=True, null=True)),
                ('previous_employed', models.BooleanField(blank=True, null=True)),
                ('date_employed', models.CharField(blank=True, max_length=9)),
                ('current_employed', models.BooleanField(blank=True, null=True)),
                ('acceptance', models.BooleanField(blank=True, null=True)),
                ('signature_captured', models.CharField(blank=True, max_length=20)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('dept_code', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentsection',
            constraint=models.UniqueConstraint(fields=('ric_student', 'dept_code'), name='unique_application'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='application_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sef.studentsection'),
        ),
    ]
