# Generated by Django 3.2.7 on 2021-10-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0002_alter_employersection_award_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersection',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
