# Generated by Django 3.2.7 on 2021-10-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0003_alter_employersection_begin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersection',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='rate_of_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
