# Generated by Django 3.2.7 on 2021-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0004_auto_20211015_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersection',
            name='acct_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='agency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='dept_grant_no',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='dept_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='grant_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='hire_period',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='job_loc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='name_dept_head',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='pay_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='pos_sched',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='pos_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='resp_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='responsible',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employersection',
            name='source_funds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
