# Generated by Django 3.2.7 on 2021-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0008_alter_employersection_award_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_dept'),
        ),
    ]
