# Generated by Django 3.2.7 on 2021-10-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0009_auto_20211021_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='dept_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sef.department'),
        ),
    ]
