# Generated by Django 3.2.7 on 2021-10-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0010_auto_20211021_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='dept_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
