# Generated by Django 3.2.7 on 2021-10-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0011_alter_studentsection_dept_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='dept_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sef.department'),
        ),
    ]
