# Generated by Django 3.2.7 on 2021-10-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0013_alter_employersection_award_amt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_dept',
        ),
    ]
