# Generated by Django 3.2.7 on 2021-10-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0014_remove_department_unique_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='email_used',
            field=models.EmailField(blank=True, max_length=45),
        ),
    ]
