# Generated by Django 3.2.7 on 2021-10-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0016_cdcsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcsection',
            name='date_linked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
