# Generated by Django 3.2.7 on 2021-10-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0018_cdcsection_date_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.CharField(blank=True, max_length=50)),
                ('application_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sef.employersection')),
            ],
        ),
    ]
