# Generated by Django 3.2.7 on 2021-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0019_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='class_schedule',
            new_name='claims',
        ),
        migrations.AddField(
            model_name='attachments',
            name='drug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachments',
            name='i9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachments',
            name='identification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachments',
            name='schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachments',
            name='w4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachments',
            name='work_study',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
