# Generated by Django 3.2.7 on 2021-11-02 23:19

from django.db import migrations, models
import sef.models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0021_auto_20211102_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='identification',
            field=models.ImageField(blank=True, upload_to=sef.models.studentmedia),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='schedule',
            field=models.ImageField(blank=True, upload_to=sef.models.studentmedia),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='work_study',
            field=models.ImageField(blank=True, upload_to=sef.models.studentmedia),
        ),
    ]
