# Generated by Django 3.2.7 on 2021-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0022_auto_20211102_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='signature_url',
            field=models.TextField(blank=True),
        ),
    ]
