# Generated by Django 3.2.7 on 2021-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0024_remove_studentsection_signature_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='signature_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
