# Generated by Django 3.2.7 on 2021-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0025_alter_studentsection_signature_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersection',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
