# Generated by Django 3.2.7 on 2021-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0026_alter_employersection_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcsection',
            name='payroll_sign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
