# Generated by Django 3.2.7 on 2021-12-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sef', '0027_alter_cdcsection_payroll_sign'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentsection',
            index=models.Index(fields=['application', 'ric_student', 'last_name', 'first_name'], name='sef_student_applica_5263d3_idx'),
        ),
    ]
